gym/gym/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Index
    path('', views.HomePage.as_view(), name='home'),
    # Routines
    path('routines/', include('routines.urls', namespace='routines')),
]

gym/routines/urls.py
from django.urls import path
from . import views

app_name = 'routines'

urlpatterns = [
    path('', views.RoutineListView.as_view(), name='routine_list'),
    path('<int:pk>/', views.RoutineDetailView.as_view(), name='routine_detail'),
    path('new/', views.CreateRoutineView.as_view(), name='routine_new'),
    path('<int:pk>/edit/', views.RoutineUpdateView.as_view(), name='routine_edit'),
    path('<int:pk>/remove/', views.RoutineDeleteView.as_view(), name='routine_remove'),
    path('new_exercise/', views.CreateExerciseView.as_view(), name='exercise_new'),
    path('exercise/<int:pk>/edit/', views.ExerciseUpdateView.as_view(), name='exercise_edit'),
    path('exercise/<int:pk>/remove/', views.ExerciseDeleteView.as_view(), name='exercise_remove'),
]

gym/routines/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Routine(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("routines:routine_detail",kwargs={'pk':self.pk})


class Exercise(models.Model):
    routine = models.ForeignKey('routines.Routine',related_name='exercises',on_delete=models.CASCADE)
    name = models.CharField(max_length=255, unique=True)
    reps = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("routines:exercise_new")

gym/routines/forms.py
from django import forms
from routines.models import Routine, Exercise

class RoutineForm(forms.ModelForm):
    class Meta():
        model = Routine
        fields = ('name', )


class ExerciseForm(forms.ModelForm):
    class Meta():
        model = Exercise
        fields = ('routine', 'name', 'reps', 'weight')

gym/gym/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

gym/routines/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from routines.models import Routine, Exercise
from routines.forms import RoutineForm, ExerciseForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  DeleteView, UpdateView,)

# Create your views here.
class RoutineListView(ListView):
    model = Routine

class RoutineDetailView(DetailView):
    model = Routine

class CreateRoutineView(CreateView):
    redirect_field_name = 'routines/routine_detail.html'

    form_class = RoutineForm

    model = Routine

class RoutineUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'routines/routine_detail.html'

    form_class = RoutineForm

    model = Routine

class RoutineDeleteView(DeleteView):
    model = Routine

    success_url = reverse_lazy('routines:routine_list')

class CreateExerciseView(CreateView):
    redirect_field_name = 'routines/routine_list.html'

    form_class = ExerciseForm

    model = Exercise

class ExerciseUpdateView(UpdateView):
    login_url = '/login/'
    redirect_field_name = 'routines/routine_detail.html'

    form_class = ExerciseForm

    model = Exercise

class ExerciseDeleteView(DeleteView):
    model = Exercise

    success_url = reverse_lazy('routines:routine_list')

gym/routines/templates/routines/exercise_confirm_delete.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>

{% endblock %}

gym/routines/templates/routines/exercise_form.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <div class="col-md-8">
    <h1>New Exercise</h1>

    <form class="post-form" method="POST">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-primary save">Save</button>
    </form>

  </div>
{% endblock %}

gym/routines/templates/routines/routine_base.html
{% extends "base.html" %}
{% block content %}

  <div class="container full-routine">
    <div class="row">
      {% block preroutine %}{% endblock %}
      {% block routine_content %}{% endblock %}
      {% block routine_post %}{% endblock %}
    </div>
  </div>

{% endblock %}

gym/routines/templates/routines/routine_confirm_delete.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>

{% endblock %}

gym/routines/templates/routines/routine_detail.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <div class="col-md-12">
    <!-- Routine -->
    <div class="jumbotron">
      <h1 class='display-4'>{{ routine.name }}</h1>

      <!-- Routine Buttons -->
      {% if user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'routines:exercise_new'%}">Create Exercise</a>
        <a class="btn btn-warning" href="{% url 'routines:routine_edit' pk=routine.pk %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'routines:routine_remove' pk=routine.pk %}">Remove</a>
      {% endif %}

      <hr>

      <!-- Exercise -->
      <h2>Exercises:</h2>

      {% for exercise in routine.exercises.all %}
        <br>
        <p><strong>{{exercise.name}}</strong> ({{ exercise.reps }} repetitions - {{exercise.weight}}kg)
          <!-- Exercise Buttons -->
          {% if user.is_authenticated %}
            <a class="btn btn-warning btn-sm" href="{% url 'routines:exercise_edit' pk=exercise.pk %}">Edit</a>
            <a class="btn btn-danger btn-sm" href="{% url 'routines:exercise_remove' pk=exercise.pk %}">Remove</a>
          {% endif %}
        </p>
      {% empty %}
        <p>No exercises</p>
      {% endfor %}
    </div>

  </div>
{% endblock %}

gym/routines/templates/routines/routine_form.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <div class="col-md-8">
    <h1>New Routine</h1>
    <br>

    <form class="post-form" method="POST">
      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit" class="btn btn-primary save">Save</button>
    </form>

  </div>
{% endblock %}

gym/routines/templates/routines/routine_list.html
{% extends "routines/routine_base.html" %}
{% block routine_content %}
  <div class="col-md-12">
    {% for routine in routine_list %}
      <div class="jumbotron">
        <h1><a class="name" href="{% url 'routines:routine_detail' pk=routine.pk %}">{{ routine.name }}</a>
          {% if user.is_authenticated %}
            <a class="btn btn-warning" href="{% url 'routines:routine_edit' pk=routine.pk %}">Edit</a>
            <a class="btn btn-danger" href="{% url 'routines:routine_remove' pk=routine.pk %}">Remove</a>
          {% endif %}
        </h1>
      </div>
    {% endfor %}
  </div>
{% endblock %}

gym/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Gym</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">
        <i class="material-icons">offline_bolt</i></a>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Routines
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'routines:routine_list' %}">All Routines</a>
            <a class="dropdown-item" href="{% url 'routines:routine_new' %}">Create Routine</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'routines:exercise_new' %}">Create Exercise</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
    </nav>




    <div class="tester">
      {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

gym/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Welcome</h1>
{% endblock %}